version: '3'

services:
    db:
        container_name: database
        image: mysql:8.0.29
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: marvel
        ports:
            - 3306
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - marvel

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin:5.2.0
        restart: always
        ports:
            - 8001:80
        environment:
            - PMA_HOST=db
        networks:
            - marvel

    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080

volumes:
    db-data:

networks:
    marvel:
